sonar.projectKey=student-crud
sonar.projectName=Student CRUD Project
sonar.projectVersion=1.0

# Source Code Location
sonar.sources=.

# Source Encoding
sonar.sourceEncoding=UTF-8

# PHP Version
sonar.php.version=8.2

# Exclude folders
sonar.exclusions=**/vendor/**,**/node_modules/**

# Language
sonar.language=php